2015-07-07 11:23:31,786 [main@zmyth.xlib.Start] INFO  zmyth.back.Main - start, parse file=server.xml
2015-07-07 11:23:31,786 [main@zmyth.xlib.Start] INFO  zmyth.back.Main - start, parse file=server.xml
2015-07-07 11:23:31,826 [main@zmyth.xlib.Start] INFO  zmyth.back.Main - start, parse file=[resource]serverconfig.xml
2015-07-07 11:23:31,826 [main@zmyth.xlib.Start] INFO  zmyth.back.Main - start, parse file=[resource]serverconfig.xml
2015-07-07 11:23:32,633 [main@zmyth.xlib.Start] WARN  zmyth.orm.ConnectionManager - init, driver=com.mysql.jdbc.Driver, url=jdbc:mysql://localhost/zsg_bi_rc
java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1055)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3491)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3423)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:910)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:3923)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1273)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2031)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:718)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:46)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:302)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:282)
	at java.sql.DriverManager.getConnection(DriverManager.java:582)
	at java.sql.DriverManager.getConnection(DriverManager.java:154)
	at zmyth.orm.ConnectionManager.init(ConnectionManager.java:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at zlib.field.FieldKit.invoke(FieldKit.java:342)
	at zmyth.xml.MethodParser.normalParse(MethodParser.java:151)
	at zmyth.xml.NormalParser.parse(NormalParser.java:110)
	at zmyth.xml.ObjParser.parseMacro(ObjParser.java:88)
	at zmyth.xml.ObjParser.normalParse(ObjParser.java:52)
	at zmyth.xml.NormalParser.parse(NormalParser.java:110)
	at zmyth.xml.ObjectsParser.parseLoad(ObjectsParser.java:93)
	at zmyth.xml.ObjectsParser.parseMacro(ObjectsParser.java:58)
	at zmyth.xml.ObjectsParser.parse(ObjectsParser.java:37)
	at zmyth.xml.ClassNameXmlContext.parse(ClassNameXmlContext.java:430)
	at zmyth.xml.ClassNameXmlContext.parse(ClassNameXmlContext.java:423)
	at zmyth.back.Main.start(Main.java:264)
	at zmyth.back.Main.run(Main.java:79)
	at zmyth.xlib.Start.run(Start.java:134)
	at zmyth.xlib.Start.main(Start.java:60)
2015-07-07 11:23:32,644 [main@zmyth.xlib.Start] WARN  zmyth.xml.MethodParser - normalParse error, method invoke, zlib.xml.Element@adb1d4[count=0][line=36, name=method, attributes=1]
java.lang.RuntimeException: zlib.field.FieldKit invoke, invoke, class=zmyth.orm.ConnectionManager, object=zmyth.orm.ConnectionManager@17e4ca[driver=com.mysql.jdbc.Driver, url=jdbc:mysql://localhost/zsg_bi_rc, run=0, size=0, maxSize=1000, timeout=180000, maxUsedCount=20000, autoCommit=false, check=true], methodName=init args=0
	at zlib.field.FieldKit.invoke(FieldKit.java:346)
	at zmyth.xml.MethodParser.normalParse(MethodParser.java:151)
	at zmyth.xml.NormalParser.parse(NormalParser.java:110)
	at zmyth.xml.ObjParser.parseMacro(ObjParser.java:88)
	at zmyth.xml.ObjParser.normalParse(ObjParser.java:52)
	at zmyth.xml.NormalParser.parse(NormalParser.java:110)
	at zmyth.xml.ObjectsParser.parseLoad(ObjectsParser.java:93)
	at zmyth.xml.ObjectsParser.parseMacro(ObjectsParser.java:58)
	at zmyth.xml.ObjectsParser.parse(ObjectsParser.java:37)
	at zmyth.xml.ClassNameXmlContext.parse(ClassNameXmlContext.java:430)
	at zmyth.xml.ClassNameXmlContext.parse(ClassNameXmlContext.java:423)
	at zmyth.back.Main.start(Main.java:264)
	at zmyth.back.Main.run(Main.java:79)
	at zmyth.xlib.Start.run(Start.java:134)
	at zmyth.xlib.Start.main(Start.java:60)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at zlib.field.FieldKit.invoke(FieldKit.java:342)
	... 14 more
Caused by: java.lang.RuntimeException: zmyth.orm.ConnectionManager@17e4ca init, driver=com.mysql.jdbc.Driver, url=jdbc:mysql://localhost/zsg_bi_rc
	at zmyth.orm.ConnectionManager.init(ConnectionManager.java:195)
	... 19 more
Caused by: java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1055)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3491)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3423)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:910)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:3923)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1273)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2031)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:718)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:46)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:302)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:282)
	at java.sql.DriverManager.getConnection(DriverManager.java:582)
	at java.sql.DriverManager.getConnection(DriverManager.java:154)
	at zmyth.orm.ConnectionManager.init(ConnectionManager.java:184)
	... 19 more
2015-07-07 11:23:32,721 [main@zmyth.xlib.Start] INFO  zmyth.back.Main - start, parse file=[resource]serverport.xml
2015-07-07 11:23:32,721 [main@zmyth.xlib.Start] INFO  zmyth.back.Main - start, parse file=[resource]serverport.xml
2015-07-07 11:23:32,724 [main@zmyth.xlib.Start] INFO  zmyth.back.Main - 

server is start!


2015-07-07 11:23:32,724 [main@zmyth.xlib.Start] INFO  zmyth.back.Main - 

server is start!


2015-07-07 11:29:53,707 [main@zmyth.xlib.Start] INFO  zmyth.back.Main - start, parse file=server.xml
2015-07-07 11:29:53,707 [main@zmyth.xlib.Start] INFO  zmyth.back.Main - start, parse file=server.xml
2015-07-07 11:29:53,716 [main@zmyth.xlib.Start] INFO  zmyth.back.Main - start, parse file=[resource]serverconfig.xml
2015-07-07 11:29:53,716 [main@zmyth.xlib.Start] INFO  zmyth.back.Main - start, parse file=[resource]serverconfig.xml
2015-07-07 11:29:53,962 [main@zmyth.xlib.Start] INFO  zmyth.back.Main - start, parse file=[resource]serverport.xml
2015-07-07 11:29:53,962 [main@zmyth.xlib.Start] INFO  zmyth.back.Main - start, parse file=[resource]serverport.xml
2015-07-07 11:29:53,966 [main@zmyth.xlib.Start] INFO  zmyth.back.Main - 

server is start!


2015-07-07 11:29:53,966 [main@zmyth.xlib.Start] INFO  zmyth.back.Main - 

server is start!


